// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oimbqgyhpcqkqorekhvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pbWJxZ3locGNxa3FvcmVraHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MzU4NzUsImV4cCI6MjA1NTQxMTg3NX0.dsb-Zg5SRjGDiwNLad26H47lwlALGVoqMlEVS0MFy5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);